language: generic
env:
  matrix:
    - EVMVERSION=emacs-25.1-travis
    - EVMVERSION=emacs-24.4-travis
before_install:
  - source travis-evm-cask.sh
install:
  # Install our packages
  - make compile
script:
  # Run the unit tests
  - make test
